exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: noir-theme

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: iced water
description: rithika
