title: iced water
description: rithika
theme: jekyll-theme-primer

exclude:
  - node_modules
  - script

sass:
  style: :compressed

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
